spring:
  application:
    name: ORDER
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8000

logging:
  file:
    name: C:/elk_logs/sonizone-elk-stack.log