spring:
  application:
    name: PAYMENT

  kafka:
    bootstrap-servers: localhost:9092           #my-kafka.kafka.svc.cluster.local:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  #Correct for JSON
      properties:
        spring.json.trusted.packages: "*"  # Allow all packages (or use `com.example`)

server:
  port: 8001

logging:
  file:
    name: C:/elk_logs/sonizone-elk-stack.log